[project]
name = "roker"
version = "0.1.0"
description = "poker bot thing"
packages = [
    { include = "roker" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "roker.api.main:start"
